name: Hurl Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Hurl
        uses: gacts/install-hurl@v1

      - name: Run Hurl Tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: npm run tests
          start: cargo build
